
%dw 2.0
output application/java 
---
{
  Id : "141c91fc22a54130b99",
  IsDeleted : true,
  MasterRecordId : "461bcf2a136243e180e",
  Name : "Abbey",
  Type : "Other",
  ParentId : "7533581b7b2b421289b",
  BillingStreet : "consequatur,",
  BillingCity : "consequuntur",
  BillingState : "reprehenderit",
  BillingPostalCode : "qui",
  BillingCountry : "ipsa",
  BillingLatitude : 5,
  BillingLongitude : 87,
  BillingGeocodeAccuracy : "County",
  BillingAddress : {
    city : "Madrid",
    country : "Lesotho",
    countryCode : "Mexico",
    latitude : 9,
    longitude : 99,
    postalCode : "Ut",
    state : "vel",
    stateCode : "",
    street : "Geary St 86",
  },
  ShippingStreet : "fugit,",
  ShippingCity : "consectetur",
  ShippingState : "enim",
  ShippingPostalCode : "quam",
  ShippingCountry : "sit",
  ShippingLatitude : 21,
  ShippingLongitude : 96,
  ShippingGeocodeAccuracy : "Block",
  ShippingAddress : {
    city : "Chicago",
    country : "Estonia",
    countryCode : "Bulgaria",
    latitude : 96,
    longitude : 19,
    postalCode : "eiusmod",
    state : "modi",
    stateCode : "pariatur?",
    street : "Geary St 20",
  },
  Phone : "(624)-413-7499",
  Fax : "(644)-362-4438",
  AccountNumber : "ea",
  Website : "sit",
  PhotoUrl : "http://acme.com/8772118",
  Sic : "commodi",
  Industry : "Utilities",
  AnnualRevenue : 51,
  NumberOfEmployees : 44,
  Ownership : "Public",
  TickerSymbol : "sit",
  Description : "molestiae est, pariatur? natus ut aliquam ullam Nemo incidunt id dolore et inventore quaerat fugiat aute veniam, illo sunt ",
  Rating : "Warm",
  Site : "quia",
  OwnerId : "ada5d725b11d42b4bb7",
  CreatedDate : |2016-01-17T05:14:11Z|,
  CreatedById : "5a60c15576804925a48",
  LastModifiedDate : |2014-01-05T14:18:38Z|,
  LastModifiedById : "26079d72680d4ad6b43",
  SystemModstamp : |2008-09-04T20:15:08Z|,
  LastActivityDate : |2002-02-02|,
  LastViewedDate : |2015-06-13T06:22:47Z|,
  LastReferencedDate : |2009-03-07T17:09:46Z|,
  Jigsaw : "ad",
  JigsawCompanyId : "cb91e3b7230e44609df",
  CleanStatus : "Inactive",
  AccountSource : "Purchased List",
  DunsNumber : "magna",
  Tradestyle : "ipsa",
  NaicsCode : "veniam,",
  NaicsDesc : "labore",
  YearStarted : "non",
  SicDesc : "sit",
  DandbCompanyId : "d11d322846b0455aa0d",
  OperatingHoursId : "0665f027c2b84cf3bd6",
  CustomerPriority__c : "High",
  SLA__c : "Silver",
  Active__c : "Yes",
  NumberofLocations__c : 45,
  UpsellOpportunity__c : "No",
  SLASerialNumber__c : "incidunt",
  SLAExpirationDate__c : |2017-02-06|,
  fieldsToNull : ["sed",
    "dolorem"],
}
